APPS = [
    "silk",
    "cacheops",
    "rest_framework",
    "corsheaders",
    "django_filters",
    "rosetta",
    "django_redis",
    "rest_framework_simplejwt",
    "django_ckeditor_5",
    "drf_spectacular",
    "core.apps.accounts",
    "adminsortable2",
    "django_core",
]
