# Generated by Django 5.1.3 on 2024-12-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='balance'),
        ),
    ]
