networks:
  seezntv:
    driver: bridge
  dokploy-network:
    external: true

services:
  nginx:
    networks:
      - seezntv
      - dokploy-network
    ports:
      - ${PORT:-8001}:80
    volumes:
      - ./resources/layout/nginx.conf:/etc/nginx/nginx.conf
      - ./resources/:/usr/share/nginx/html/resources/
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
  web:
    networks:
      - seezntv
      - dokploy-network
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    restart: always
    command: ${COMMAND:-sh ./entrypoint.sh}
    volumes:
      - .:/code
      - ../files/resources:/code/resources
    depends_on:
      - db
      - redis
