# Generated by Django 5.1.3 on 2024-12-14 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreaksItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cadr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadr', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IstoryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources', models.URLField()),
                ('skip_start_time', models.DurationField(blank=True, null=True)),
                ('skip_end_time', models.DurationField(blank=True, null=True)),
                ('index', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BreakList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ManyToManyField(blank=True, to='content.breaksitem')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.categoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_desktop', models.URLField()),
                ('poster_mobile', models.URLField()),
                ('poster_card', models.URLField()),
                ('poster_video', models.URLField()),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('age_limit', models.PositiveIntegerField()),
                ('release_date', models.DateField()),
                ('upload_at', models.DateField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='content.categorylist')),
                ('kadrs', models.ManyToManyField(blank=True, to='content.cadr')),
            ],
        ),
        migrations.AddField(
            model_name='breaksitem',
            name='break_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.content'),
        ),
        migrations.CreateModel(
            name='GenreList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.genreitem')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='genre',
            field=models.ManyToManyField(to='content.genrelist'),
        ),
        migrations.CreateModel(
            name='Istory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.content')),
                ('videos', models.ManyToManyField(to='content.istoryvideo')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, to='content.tag'),
        ),
        migrations.AddField(
            model_name='content',
            name='chronology',
            field=models.ManyToManyField(blank=True, related_name='chronology', to='content.videocontent'),
        ),
        migrations.AddField(
            model_name='content',
            name='contents',
            field=models.ManyToManyField(related_name='contents', to='content.videocontent'),
        ),
        migrations.AddField(
            model_name='content',
            name='ova',
            field=models.ManyToManyField(blank=True, related_name='ova', to='content.videocontent'),
        ),
    ]
