# Generated by Django 5.1.3 on 2024-12-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryItem',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='GenreItem',
            new_name='Genre',
        ),
        migrations.RemoveField(
            model_name='breaksitem',
            name='break_item',
        ),
        migrations.RemoveField(
            model_name='categorylist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='genrelist',
            name='genre',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='item',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='item',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ManyToManyField(blank=True, to='content.content')),
            ],
        ),
        migrations.DeleteModel(
            name='BreakList',
        ),
        migrations.DeleteModel(
            name='BreaksItem',
        ),
        migrations.DeleteModel(
            name='CategoryList',
        ),
        migrations.DeleteModel(
            name='GenreList',
        ),
    ]
