# Generated by Django 5.1.3 on 2024-12-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_categoryitem_category_rename_genreitem_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ManyToManyField(to='content.category'),
        ),
        migrations.AlterField(
            model_name='content',
            name='genre',
            field=models.ManyToManyField(to='content.genre'),
        ),
    ]
