# Generated by Django 5.1.3 on 2024-12-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.BooleanField(default=False, verbose_name='status'),
        ),
    ]
