# Generated by Django 5.1.3 on 2024-12-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='payment_method',
            field=models.CharField(choices=[('click', 'click'), ('paynet', 'payment'), ('payme', 'payme'), ('manual', 'manual')], default='click', verbose_name='payemnt method'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('pending', 'pending'), ('active', 'active'), ('finished', 'finished')], default='created', verbose_name='status'),
        ),
    ]
