# Generated by Django 5.1.3 on 2024-12-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='istorymodel',
            name='content',
        ),
        migrations.RemoveField(
            model_name='istorymodel',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='istorymodel',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='istorymodel',
            name='content_uz',
        ),
        migrations.AddField(
            model_name='istorymodel',
            name='desc',
            field=models.TextField(default=1, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='istorymodel',
            name='desc_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='istorymodel',
            name='desc_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='istorymodel',
            name='desc_uz',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='istorymodel',
            name='image',
            field=models.ImageField(null=True, upload_to='istory/', verbose_name='image'),
        ),
    ]
