# Generated by Django 5.1.3 on 2024-12-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="contentmodel",
            table="content",
        ),
    ]
