# Generated by Django 5.1.3 on 2024-12-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('desc', models.TextField(verbose_name='desc')),
            ],
            options={
                'verbose_name': 'PostModel',
                'verbose_name_plural': 'PostModels',
                'db_table': 'post',
            },
        ),
        migrations.AlterField(
            model_name='intervalmodel',
            name='items',
            field=models.ManyToManyField(to='api.mediamodel', verbose_name='items'),
        ),
        migrations.AlterField(
            model_name='istorymodel',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
    ]
