# Generated by Django 5.1.3 on 2024-12-18 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_istorymodel_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='api.commentmodel'),
        ),
    ]
