# Generated by Django 5.1.3 on 2024-12-05 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_postmodel_alter_intervalmodel_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=255, verbose_name='content')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contentmodel', verbose_name='film')),
            ],
            options={
                'verbose_name': 'BannerModel',
                'verbose_name_plural': 'BannerModels',
                'db_table': 'banner',
            },
        ),
    ]
