# Generated by Django 5.1.3 on 2024-12-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_contentmodel_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadrmodel",
            name="image",
            field=models.FileField(max_length=255, upload_to="cadr/", verbose_name="image"),
        ),
    ]
