# Generated by Django 5.1.3 on 2024-12-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_contentmodel_poster_card_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediamodel",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="name"),
        ),
    ]
