# Generated by Django 5.1.3 on 2024-12-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mediamodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='video',
            field=models.CharField(max_length=255, verbose_name='video'),
        ),
    ]
