# Generated by Django 5.1.3 on 2024-12-05 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_mediamodel_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.CharField(max_length=255, verbose_name='video')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('skip_start_time', models.DurationField(blank=True, null=True, verbose_name='skip_start_time')),
                ('skip_end_time', models.DurationField(blank=True, null=True, verbose_name='skip_end_time')),
                ('position', models.PositiveIntegerField(blank=True, null=True, verbose_name='position')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contentmodel', verbose_name='content')),
            ],
            options={
                'verbose_name': 'VideoModel',
                'verbose_name_plural': 'VideoModels',
                'db_table': 'video',
            },
        ),
    ]
