# Generated by Django 5.1.3 on 2024-12-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_videomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentmodel',
            name='contents',
        ),
    ]
