# Generated by Django 5.1.3 on 2024-12-05 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_videomodel_options_alter_videomodel_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervalmodel",
            name="content",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.contentmodel", verbose_name="content"
            ),
        ),
    ]
