# Generated by Django 5.1.3 on 2024-12-06 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_intervalmodel_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="cadrmodel",
            name="content",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="api.contentmodel"),
        ),
    ]
