# Generated by Django 5.1.3 on 2024-12-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_contentmodel_cadrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadrmodel',
            name='image',
            field=models.ImageField(max_length=255, upload_to='cadr/', verbose_name='image'),
        ),
    ]
